# -*- coding: utf-8 -*-
"""Students_Performance_Odev.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gHKE7VGypCWCIfBmvpdWl1tsxvXqGZvr
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

#1
df = #dosyayı okuyalım
df.head()

#2
#kadın-erkek sayısına bakalım

#3
#kadın-erkek sayısına histogram grafiği ile bakalım

#4
#race/ethnicity sütununda kaç farklı grup olduğuna bakalım

race = df["race/ethnicity"].value_counts()
race

#5
#yukarıda bulduğumuzu görselleştirelim

#6
#parental level of education sütunundaki eşsiz değerleri bulalım

df["parental level of education"].value_counts()

#7
#lunch sütununda eşsiz değerlere ulaşalım

#8
#lunch türlerinde kaçar kişi olduğunu bulalım

df["test preparation course"].value_counts()

#9
#gender sütunundaki değerler için ortalama math score, reading score, writing score değerlerini bulalım.

#10
#race/ethnicity sütunundaki değerler için ortalama math score, reading score, writing score değerlerini bulalım.

#11
#parental level of education sütunundaki değerler için ortalama math score, reading score, writing score değerlerini bulalım.

#12
#lunch sütunundaki değerler için ortalama math score, reading score, writing score değerlerini bulalım.

#13
#test preparation coursesütunundaki değerler için ortalama math score, reading score, writing score değerlerini bulalım.

